# Generated by Django 5.0.6 on 2024-09-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='amount',
        ),
    ]
